services:
  nginx:
    image: nginx:stable-alpine # Usamos la imagen directa en lugar de 'build'
    ports:
      - "${PORT_NGINX}:${PORT_NGINX}"
    volumes:
      # Montamos tu archivo de configuración directamente
      - ./frontend/proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Montamos los certificados SSL (muy importante para tu config)
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    networks:
      - prod-network
    restart: unless-stopped

  backend:
    build: ./backend
    # La guia demana el port 8088 per a producció
    environment:
      - NODE_ENV=production
      - PORT=8088
    networks:
      - prod-network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - prod-network
    restart: always

networks:
  prod-network:
    driver: bridge